### ISSUE TITLE
手机客户端错误提示

### ISSUE THREAD

**Issue by Mr-Chatwin** [RikkaApps/FCM-for-Mojo#101]
手机客户端服务器已正常连接，点击加号添加设备时显示“无法获取令牌....”，“正在尝试请求然后提示出错了：server not available” 请问是哪里出现了问题，手机设备不支持吗？

**Comment by WordlessEcho** [comment]
服务端有错误日志吗？

**Comment by Mr-Chatwin** [comment]
无报错日志仅有一句[FFM] /ffm/get_registration_ids
![image](https://user-images.githubusercontent.com/21234158/35474334-dc54e78c-03c7-11e8-94e5-891203bd1ef0.png)
![image](https://user-images.githubusercontent.com/21234158/35474338-e364e7ca-03c7-11e8-8918-498bfcc4b403.png)
手机端报错如图

**Comment by RikkaW** [comment]
没有 Google 全家桶 吗（

**Comment by Mr-Chatwin** [comment]
有全家桶啊  手机型号三星G9300 全家桶安装了  Play都可以正常使用  是缺某一个推送软件吗？

**Comment by Mr-Chatwin** [comment]
已知原因:三星系统缺陷，已升级安卓7.0但是推送仍然是GCM不是FCM，解决方法未知。

**Comment by WordlessEcho** [comment]
使用 *#*#426#*#* 查看 FCM 的日志

**Comment by Mr-Chatwin** [comment]
三星系统特殊，用软件push notifications fixer进入后点击connect连接的一直是mtalk.google.com：443/5228，日志截图如下
![screenshot_20180128-122228](https://user-images.githubusercontent.com/21234158/35478994-6c572d00-0426-11e8-89aa-580fbd844b17.png)
![screenshot_20180128-122218](https://user-images.githubusercontent.com/21234158/35478996-7008925e-0426-11e8-9a32-0914f71bfb4b.png)

**Comment by milkice233** [comment]
@Mr-Chatwin 你这就 压根没连接到推送服务器，有挂梯子吗

**Comment by Mr-Chatwin** [comment]
对啊  就是没连接到啊  GCM才需要梯子吧  FCM也需要？而且我尝试挂了也没用。

**Comment by milkice233** [comment]
@Mr-Chatwin 在这种情况下 FCM 就是 GCM 没有任何区别
请挂上梯子后再试
