### ISSUE TITLE
希望能支持Mipush的推送方式

### ISSUE THREAD

**Issue by w1324296014** [RikkaApps/FCM-for-Mojo#104]
像gcmformojo一样，让没有谷歌服务的也能用上最新的通知栏特性，让有谷歌服务的少开一个后台😊

**Comment by YHNdnzj** [comment]
@w1324296014 不要
少開一個後台？
什麼意思

**Comment by RikkaW** [comment]
你们 MIUI 的通知特性知道 4.0 所以不存在的

**Comment by WordlessEcho** [comment]
MIUI doesn't support Android new feature (like quick reply in notification, etc), it doesn't concerned about the push services.

**Comment by WordlessEcho** [comment]
I guess you are meaning to wish FFM support [Trumeet's Mi Push framework](https://github.com/Trumeet/MiPushFramework).

1. This project is still unstable: it may damage your phone into bootloop.
2. It's high cost to add Xiaomi SDK: we need use [project Condom](https://github.com/oasisfeng/condom) to prevent the harm of user experience.
3. Additional compatibility problems: many user will think Mi Push support = MIUI support, but it's involuted to deal with MIUI's notification.

**Comment by w1324296014** [comment]
谢谢大神们的回复，我目前确实在用着Trumeet's Mi Push framework，支持一些app，所以不想为了ffm再刷一个谷歌服务了... ...
