### ISSUE TITLE
群推送白名单问题

### ISSUE THREAD

**Issue by Hzbeta** [RikkaApps/FCM-for-Mojo#117]
有时候mojoWebqq获取不到群号码，但是可以通过群名称设置白名单。
现在当群号码获取不到时，就无法设置白名单，能不能加一个功能，可以在获取不到群号码时，使用群名称作为白名单呢？讨论组同理。

**Comment by imal1** [comment]
可以在client.js里修改，只不过客户端还是不好控制了

**Comment by Hzbeta** [comment]
现在可以通过设置QQ号和密码来达到在扫码登录时也可以获取uid了，祥见https://github.com/sjdy521/Mojo-Webqq/issues/183
