### ISSUE TITLE
客户端无法连接服务器

### ISSUE THREAD

**Issue by IcySakura** [RikkaApps/FCM-for-Mojo#118]
执行npm start后，登录正常，但登录之后出现了[FFM] do not send because ids is empty，不过消息接受正常。
当使用客户端尝试连接服务器时，不论更换为什么端口都无法成功连接。
使用的是Vultr的服务器，系统是CentOS 7 x64.

**Comment by YHNdnzj** [comment]
@IcySakura 你服務端設置的端口是什麼

**Comment by IcySakura** [comment]
@YHNdnzj 是默认的5003，5004，5005，也尝试过其他的（9001，9002，9003），都无法正常连接。

**Comment by IcySakura** [comment]
![image](https://user-images.githubusercontent.com/18676012/39659855-f3f53980-4fe6-11e8-9c76-bbf78c9813dc.png)
这个是运行服务端时的截图

**Comment by YHNdnzj** [comment]
@IcySakura 你開放端口了嗎

**Comment by WordlessEcho** [comment]
请问你有在手机端上添加设备了吗？如果可以，请把手机端的设备列表截图和服务端的 config.json 贴上来，请注意做**打码处理**

**Comment by IcySakura** [comment]
@YHNdnzj 已经使用sudo firewall-cmd --zone=public --add-port=****/tcp --permanent命令开放了端口，但是无用。

**Comment by YHNdnzj** [comment]
@IcySakura 重啟 firewalld 了嗎

**Comment by IcySakura** [comment]
@WordlessEcho 问题已经解决了，谢谢 （忘记重启firewall了）

**Comment by IcySakura** [comment]
@YHNdnzj 多谢提醒，已经解决了
