### ISSUE TITLE
无法获取头像是什么原因

### ISSUE THREAD

**Issue by DoveKi** [RikkaApps/FCM-for-Mojo#121]
其他功能都正常，就设置里更新头像功能点了没反应，通知栏闪一下就没了

**Comment by RikkaW** [comment]
@DoveKi 分群组设置里面会有 无法获取 uid 吗（

**Comment by DoveKi** [comment]
@RikkaW 嗯对 分群组是无法获取群号 不过群消息正常接收

**Comment by RikkaW** [comment]
@DoveKi 根据这个做吧 https://github.com/sjdy521/Mojo-Webqq/issues/183 （
