### ISSUE TITLE
nodejs更新后无法运行了……

### ISSUE THREAD

**Issue by godspirit00** [RikkaApps/FCM-for-Mojo#127]
提示如下：
> ffm@0.7.0 start /root/FCM-for-Mojo-Server
> node node/index.js
>
>/root/FCM-for-Mojo-Server/node/index.js:141
>    let body;
>    ^^^
>
>SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
>    at exports.runInThisContext (vm.js:53:16)
>    at Module._compile (module.js:373:25)
>    at Object.Module._extensions..js (module.js:416:10)
>    at Module.load (module.js:343:32)
>    at Function.Module._load (module.js:300:12)
>    at Function.Module.runMain (module.js:441:10)
>    at startup (node.js:140:18)
>    at node.js:1043:3
>npm ERR! code ELIFECYCLE
>npm ERR! errno 1
>npm ERR! ffm@0.7.0 start: `node node/index.js`
>npm ERR! Exit status 1
>npm ERR!
>npm ERR! Failed at the ffm@0.7.0 start script.
>npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

求解……

**Comment by haruue** [comment]
无法在 Arch Linux 上的 node v10.8.0 上复现此问题。

能提供一下您的 nodejs 版本么，可以使用下面这条命令获取：
``` shell
node --version
```

**Comment by godspirit00** [comment]
系统是Debian 9，nodejs版本是v4.8.2。

**Comment by haruue** [comment]
4.8.2 太老了。
请按这里的方法安装新版本。
https://nodejs.org/en/download/package-manager/#debian-and-ubuntu-based-linux-distributions

**Comment by godspirit00** [comment]
按照这个方法更新后正常了。抱歉，打扰了。
