### ISSUE TITLE
二维码文件写入失败是怎么回事

### ISSUE THREAD

**Issue by 1045925330** [RikkaApps/FCM-for-Mojo#128]
[error] 二维码写入文件失败: No such file or directory
[fatal] 登录失败，客户端退出（可能网络不稳定，请多尝试几次）

**Comment by WordlessEcho** [comment]
The QR code will write to /tmp in default. Check out your permission to /tmp or `qrcode_path` in perl/start.pl.

**Comment by ojhdt** [comment]
国内腾讯云推送失败，没有合适的代理
[FFM] push failed, error: Error: tunneling socket could not be established, cause=connect ECONNREF
USED 127.0.0.1:8080

**Comment by haruue** [comment]
@ojhdt 如果你打算使用代理完成对 Google FCM 的连接，你需要先配置好一个 HTTP 代理。然后把对应配置设置给配置文件中的 `push_proxy` 。
请注意配置文件中的这一行只是一个示例，仅仅把它注释掉而没有配置好代理是没有用的。
```
"push_proxy": 'http://127.0.0.1:8080',
```
目前只支持 HTTP 代理，如果你只有 SOCKS5 代理，使用 Polipo 或者 Privoxy 转发一下。

**Comment by haruue** [comment]
因为问题应该已经解决，我现在将关闭这个 Issue 。
如果问题仍然未解决，请重新打开它。
