### ISSUE TITLE
client.json文件不存在

### ISSUE THREAD

**Issue by AzunyanDaisuki** [RikkaApps/FCM-for-Mojo#139]
![image](https://user-images.githubusercontent.com/18110400/49859620-eba3ca80-fe32-11e8-9598-30191732ee1d.png)
git下来的文件里没有client.json，是什么情况

**Comment by RikkaW** [comment]
会自动建立

**Comment by WordlessEcho** [comment]
You couldn't start because of dependecies missing. Read the logs carefully.
