### ISSUE TITLE
1. 无论怎样调还是会有通知震动 2. 群里被@或者被回复不会有通知 3. 群临时会话没有通知

### ISSUE THREAD

**Issue by ShekBoy** [RikkaApps/FCM-for-Mojo#42]
手机：索尼XZ Premium
系统：官方Android 7.1.1
1. 无论怎样调还是会震
手机模式：震动模式，有铃声模式也是一样
设置：
![6f1cc66eb69e4646e888394bbfba9ea2](https://user-images.githubusercontent.com/22590886/29903891-d0198612-8e38-11e7-8f1e-b3e571ef3d14.png)
震动无论改成啥还是会震，改过优先度还是一样

2. 群里被@或者被回复(长按指定对话回复)没有通知，在终端看是确实有收到信息，但没推送到手机

3. 这个不知道是不是Webqq问题，看终端好像也没收到信息，想请问一下如果是Webqq的问题的话应该怎样设置才能收到群临时会话通知

**Comment by yEs1do** [comment]
震动那个……确定后台没挂着QQ吧？（提供一个思路）

**Comment by ShekBoy** [comment]
有挂着QQ，但确定震动跟QQ无关，因为我群都设置了接收消息但不提醒

**Comment by RikkaW** [comment]
@ShekBoy 1. 无法复现
2. 已经修了，但还没有 release
3. 不能找 Rikka

**Comment by kkren** [comment]
@ShekBoy zuk z2 pure Nexus也有这个问题，7.1.2

**Comment by WordlessEcho** [comment]
> 3 这个不知道是不是Webqq问题，看终端好像也没收到信息，想请问一下如果是Webqq的问题的话应该怎样设置才能收到群临时会话通知

你可能需要查看[上游项目的文档](https://metacpan.org/pod/distribution/Mojo-Webqq/doc/Webqq.pod)

**Comment by ShekBoy** [comment]
感谢，那我耐心等release好了
@WordlessEcho 有看过这个文档，但没法看懂…我继续研究吧，感谢

**Comment by ShekBoy** [comment]
closed了...可是我把服务端和客户端更新到最新版后群消息还是会一直有通知震动...

**Comment by RikkaW** [comment]
@ShekBoy 禁止 FFM 的通知之后会不会震动呢

**Comment by ShekBoy** [comment]
FFM设置里关掉Notification，完全没有通知，没有震动
系统的FFM应用设置里关掉通知，完全没有通知，没有震动
发现打开了系统的高级通知设置把通知调成2级可以暂时解决，不震动...
但这样的话好友消息就不能单独设置震动了
![screenshot_20170902104445](https://user-images.githubusercontent.com/22590886/29992434-6efda980-8fcd-11e7-917d-1655bfa00e2c.png)

**Comment by RikkaW** [comment]
说起来.. 现在还有问题吗..

**Comment by ShekBoy** [comment]
手机：索尼XZ Premium
系统：官方Android 8.0
@RikkaW 刚试了一下没有震动了，谢谢！
但为什么自己在群里发信息也会收到通知...？请问这正常吗？

**Comment by ShekBoy** [comment]
不好意思！刚发现并不是这边的问题，可以close了，感激！
