### ISSUE TITLE
客户端在注册设备是出现Token is null

### ISSUE THREAD

**Issue by Kotori-0912** [RikkaApps/FCM-for-Mojo#45]
Server端使用了0.3.4版本Mojo-QQ使用2.4.1，VPS已经成功运行，但是在客户端注册的时候出现Can't add Because token is null无法注册设备
![photo_2017-09-01_13-31-58](https://user-images.githubusercontent.com/25550007/29956490-1afccc7a-8f1a-11e7-9e89-d26d1d0ccc76.jpg)

**Comment by WordlessEcho** [comment]
Thiss problem not concerned about the server side.

**Comment by WordlessEcho** [comment]
1. GMS installed?
2. Cloud you connect to Google?

**Comment by Kotori-0912** [comment]
My Phone GMS is Installed ,and Can be connect to Google

**Comment by Kotori-0912** [comment]
@WordlessEcho I Find the question in my other phone（xt1095) is can registered,I Find the this phone,GMS is installed and can be connect to Google,but Google Service is not running,this is the problem

**Comment by WordlessEcho** [comment]
As Rikka says:
> FCM (GCM) 只用 Google 服务框架 用不到 play 服务 的样子

**Comment by RikkaW** [comment]
Try [v0.3.5](https://github.com/RikkaW/FCM-for-Mojo/releases/tag/v0.3.5) (added use `FirebaseInstanceId.getInstance().getToken(getString(R.string.project_id), "FCM")` to get token).
If still not work, **BLAME GOOGLE**.
