### ISSUE TITLE
Perl执行路径写死了

### ISSUE THREAD

**Issue by simonsmh** [RikkaApps/FCM-for-Mojo#56]
https://github.com/RikkaApps/FCM-for-Mojo/blob/master/server/node/mojo-webqq.js#L13
Via https://github.com/RikkaApps/FCM-for-Mojo/issues/44

可行的临时处理方法 https://github.com/RikkaApps/FCM-for-Mojo/pull/52/files

**Comment by RikkaW** [comment]
@simonsmh 那那那.. 直接去合并那个 pr.......
