### ISSUE TITLE
请求增加子路径功能

### ISSUE THREAD

**Issue by jiangming1399** [RikkaApps/FCM-for-Mojo#68]
现在服务器的设置似乎只能设置端口和域名（IP），不能设置子目录（e.g. https://xxx.xxx/xxx/）。
我这边想通过nginx反代到站点的某个的子目录，但现有的设置无法支持，希望能够完善相关设置。

**Comment by milkice233** [comment]
@jiangming1399 服务端无需变动，客户端需要修改网址匹配逻辑

**Comment by haruue** [comment]
@milkice233 客户端判断输入的 URL 合法性的时候是传给 OkHttp 。。
https://github.com/RikkaApps/FCM-for-Mojo/blob/master/app/src/main/java/moe/shizuku/fcmformojo/utils/URLFormatUtils.java#L15

**Comment by haruue** [comment]
@milkice233

**Comment by milkice233** [comment]
@haruue 这段代码我没有仔细去看，只是我前段时间也是在配置nginx反代的时候发现即便ffm客户端配置的服务端地址是https://example.com/fcm/ 似乎后面的/fcm会被忽略，所以猜测是客户端的问题，没有详细翻过代码也就得出初步结论

**Comment by jiangming1399** [comment]
@haruue 刚刚抓包发现确实是会忽略后面的子路径

**Comment by milkice233** [comment]
@jiangming1399 对的 ffm node端会输出query string，很明显和预期不相符

**Comment by haruue** [comment]
@jiangming1399 看起来是 FFService 和 OpenQQService 里多了一条斜线的问题，我修修看。。。

**Comment by RikkaW** [comment]
@haruue 好像是的诶.......

**Comment by WordlessEcho** [comment]
补充一下，其实可以反代 127.0.0.1:5001/ffm，然后 location 为 /ffm，openqq 同理

**Comment by jiangming1399** [comment]
@WordlessEcho 现在就是在用的这种方案，感觉不爽2333
