### ISSUE TITLE
[TODO] transport QR code by Node.js

### ISSUE THREAD

**Issue by WordlessEcho** [RikkaApps/FCM-for-Mojo#77]
In the past, we use [Mojo::Webqq::Plugin::UploadQRcode](https://metacpan.org/pod/distribution/Mojo-Webqq/doc/Webqq.pod#Mojo::Webqq::Plugin::UploadQRcode) module from [Mojo WebQQ](https://github.com/sjdy521/Mojo-Webqq) to upload the QR code to [Showfom's public image hosting](https://sm.ms/) to download.

Here's my thoughts to open a server that let FFM download from user's own server:

- Change download path of QR code to `perl/qrcode`.
- Mojo WebQQ return a status to Node.js to open a download server.
- Node.js push a FCM message to notify FFM to download QR code.
- Mojo WebQQ return a message to notify Node.js that login successful and close download server.

Please assign this issue to me.

**Comment by haruue** [comment]
Done.

> Change download path of QR code to perl/qrcode.
+ Now we download it from ffm/get_qr_code (handle by node)
> Mojo WebQQ return a status to Node.js to open a download server.
+ Using the same server of ffm.
> Node.js push a FCM message to notify FFM to download QR code.
+ Using origin implementation.
> Mojo WebQQ return a message to notify Node.js that login successful and close download server.
+ Don't need, Mojo-QQ will auto delete qr code file after it login, and ffm/get_qr_code will return 404.
