### ISSUE TITLE
Rikka能否考虑支持Mojo-Weixin

### ISSUE THREAD

**Issue by eldonly** [RikkaApps/FCM-for-Mojo#79]
gcmformojo的框框好难看啊，强迫症不能忍

**Comment by RikkaW** [comment]
@eldonly 不能 因为没有钱钱 以及微信信都要关了网页版了

**Comment by eldonly** [comment]
@RikkaW 好可惜啊，真的好喜欢这个app啊啊，很美观方便省电。微信网页端关闭的消息，好像tx辟谣了呀啊啊啊。。。

**Comment by WordlessEcho** [comment]
Web Weixin won't be closed.
[微信否认关闭网页版登陆 - IT 之家](https://www.ithome.com/html/it/336200.htm)
