### ISSUE TITLE
是否可以考虑增添qq电话的提醒，就像类似于[图片]的提示一样

### ISSUE THREAD

**Issue by TYPEmber** [RikkaApps/FCM-for-Mojo#80]
是否可以考虑增添qq电话的提醒，就像类似于[图片]的提示一样
或者说是否是smartqq协议本身不支持？

**Comment by milkice233** [comment]
@TYPEmber 应该是smartqq本身不支援
你可以在smartqq上登录下自己试试 如果可以的话再继续跟进此issue

**Comment by TYPEmber** [comment]
smartqq确实不支持qq电话，但是同样不支持图片的显示，但是目前这个项目是可以以[图片]形式来显示消息提醒，因此我想问一下是否可以做类似的改进？
因为，将qq完全关闭后，虽然消息能够及时收到，但是qq电话却无法接受，还挺有意义的

**Comment by WordlessEcho** [comment]
Milkice 的意思是，如果打 QQ 电话，SmartQQ 能够收到 QQ 电话的消息，这个功能就是可以做的

**Comment by TYPEmber** [comment]
@WordlessEcho 我明白了，但是我的意思是，smartqq无法收到图片，但是客户端上却可以以[图片]字样进行推送提示，所以会不会qq电话也有类似的可能？

**Comment by milkice233** [comment]
@TYPEmber 测试完毕 很遗憾当有QQ电话呼入时smartqq没有收到任何通知
这个issue可以暂时先close了 等有生之年腾讯开放接口再说吧

**Comment by TYPEmber** [comment]
@milkice233 好的，谢谢帮忙测试

**Comment by TYPEmber** [comment]
@milkice233 突然想到，那么图片发送的时候smartqq有提示吗？

**Comment by milkice233** [comment]
@TYPEmber 有的 我刚刚也做了测试
 对于图片消息在轮询的包中缺少content部分
而若是文字消息则轮询包中的content为消息内容
估计Mojo是判断content是否为null来判定图片消息的 虽然这样做很不优雅 不过目前也只能这样了

**Comment by TYPEmber** [comment]
@milkice233 好的，再次感谢
