### ISSUE TITLE
部分依赖未更新至bintray

### ISSUE THREAD

**Issue by ttimasdf** [RikkaApps/FCM-for-Mojo#83]
support-utils 位于源 https://dl.bintray.com/rikkaw/Libraries 中，未添加到gradle中，也没有2.0.3版本。
api-base 版本9也没有。

**Comment by milkice233** [comment]
@ttimasdf 就是这个嘛

**Comment by ttimasdf** [comment]
Fixed. Thanks~ 👍

**Comment by milkice233** [comment]
@ttimasdf 好耶（
