### ISSUE TITLE
可以考虑做个客户/服务端版本匹配检测？

### ISSUE THREAD

**Issue by jiangming1399** [RikkaApps/FCM-for-Mojo#84]
免得客户端与服务端版本不匹配造成crash

**Comment by haruue** [comment]
@jiangming1399 看起来客户端升级比服务端容易多了，有些用户可能还开了 Google Play 自动更新应用，然后就“莫名其妙就不能用了”。。
感觉只能在 break change 的时候发个提示要求用户升级服务端。。。

**Comment by WordlessEcho** [comment]
@haruue 其实一直想问要不要做一个自动更新服务端的功能，毕竟你们一直在 break change

**Comment by haruue** [comment]
@WordlessEcho 但是如果允许工作进程修改这些文件的话，会不会导致服务器安全问题呢。。。

**Comment by WordlessEcho** [comment]
@haruue 就是考虑到安全问题，所以没有做，可以再商讨一下

**Comment by jiangming1399** [comment]
可以弄个一键更新脚本（虽然已经够简单了）

**Comment by WordlessEcho** [comment]
这个版本检测是存在的，当服务端版本低于客户端版本，主界面会发出提示，今天这次崩溃是因为 break change 加上 Rikka 搞错了一些东西而发生的
@RikkaW 贴上 invalid 的 tag，然后 close 掉

关于服务端自动升级，一会我会新开一个 issue 来讨论

**Comment by haruue** [comment]
要不把服务端的仓库分出去，这样在服务器上 git pull 一下就能更新。。。

**Comment by RikkaW** [comment]
@haruue haruue 来 做

**Comment by haruue** [comment]
https://github.com/RikkaApps/FCM-for-Mojo-Server
然后就是更新 README
晚点我写一个吧。

**Comment by jiangming1399** [comment]
啊难怪（
那我把这个issue关掉了吧
