### ISSUE TITLE
无法收到消息

### ISSUE THREAD

**Issue by kzw200015** [RikkaApps/FCM-for-Mojo#89]
服务端一切正常，客户端也正常，查看fcm日志显示已收到推送，可就是收不到消息

**Comment by kzw200015** [comment]
PS:安卓8.0

**Comment by haruue** [comment]
提供一下客户端版本和服务端版本。另外试一下一下客户端点“停止服务端”可以收到“服务端已停止”的推送么？

**Comment by kzw200015** [comment]
@haruue 版本都是最新版0.5.1，可以收到已停止的推送
