### ISSUE TITLE
通知栏快捷回复问题

### ISSUE THREAD

**Issue by TYPEmber** [RikkaApps/FCM-for-Mojo#92]
在通知栏快捷回复的时候会有概率出现消息实际已发送，但通知栏依旧显示正在发送的转圈标志。

常见于收到消息之后，20分钟之后再回复。以及，ffm在后台长时间待机后收到推送回复时。

**Comment by WordlessEcho** [comment]
回复会直接连接到你的服务器
请确认网络没有问题

**Comment by TYPEmber** [comment]
网络应该是没有问题的，因为基本只会出现在以上两种情况下，而且实际上消息也是确实发送出去了。

2017年12月17日 01:35，"Wordless Echo" <notifications@github.com>写道：
