### ISSUE TITLE
刷机后无法接收消息

### ISSUE THREAD

**Issue by kzw200015** [RikkaApps/FCM-for-Mojo#93]
服务端正常，可是手机收不到消息，gcm日志也没有记录。我已经重新添加了设备，可是无效，服务器也重启了。我之前遇到这种情况重装服务器系统解决了，可是现在服务器上有很多东西，不便重装。我想知道如何完全卸载FCM，我已经尝试删除FCM目录然后重新安装，可是依旧无效

**Comment by haruue** [comment]
FFM 不会修改 FFM 目录与 `/tmp` 目录之外的东西。
FFM 的客户端配置存储于 FFM 服务端目录下面的 `client.json` 中。
MojoQQ 会往 `/tmp` 的下列位置写入临时文件。
```
mojo_webqq_cookie_ffm.dat
mojo_webqq_pid_ffm.pid
mojo_webqq_qrcode_ffm.png
mojo_webqq_state_ffm.json
```

请先检查你的 FFM 客户端和服务端版本是不是最新的。
如果能够成功注册设备，请在客户端“服务器管理”依次点击“停止服务器”与“重启服务器”，看看能不能收到服务器停止通知和二维码通知。
如果都不行，请提供详细的服务器端日志与 gcm 日志。

**Comment by kzw200015** [comment]
@haruue 无法收到停止通知与二维码通知，如何查看服务端的日志

**Comment by haruue** [comment]
在你的服务器上重新 attach 到你挂 ffm-server 所用的会话即可， ffm 服务端日志是直接输出到命令行的。
例如 如果你使用 `screen` 将 ffm-server 挂在服务器上，你可以使用下面的命令 attach 到之前的会话
```shell
screen -x
```
具体参考 screen 的文档，请自行 Google 。

**Comment by kzw200015** [comment]
@haruue 不好意思，问题已经解决，我卸载服务端后重启服务器再重新安装服务端就可以了，不好意思打扰了
