### ISSUE TITLE
自己发的消息也收到了通知

### ISSUE THREAD

**Issue by csho** [RikkaApps/FCM-for-Mojo#94]
一个小bug，我的安装情况是手机使用手Q，电脑端tim，配置完成后一切完美运行，在电脑端用Tim给别人发消息之后手机端的FCM收到了推送消息，是我自己发的内容，开发者有空了闲了可以处理一下。
我的QQ好友里是有自己的，不知道跟这有没有关系。

**Comment by sjdhome** [comment]
我也这样，貌似FFM.pm里的判断没做好

**Comment by Mr-Bubble** [comment]
@sjdhome https://github.com/sjdy521/Mojo-Webqq/issues/181

**Comment by RikkaW** [comment]
更新服务端到 0.5.2
