### ISSUE TITLE
Mojo-Webqq那边更新了 这边不跟进吗.

### ISSUE THREAD

**Issue by snow-dream** [RikkaApps/FCM-for-Mojo#97]
现在导致无法获取群消息 这边不跟进更新吗.

**Comment by RikkaW** [comment]
@snow-dream https://github.com/sjdy521/Mojo-Webqq/issues/183 照这个做 嘛（

**Comment by kzw200015** [comment]
@RikkaW 我照做了，可到最后一步我在start.pl中添加了上面所说的语句却没有效果啊

**Comment by snow-dream** [comment]
@kzw200015 同无效,目前还在努力折腾(

**Comment by snow-dream** [comment]
@RikkaW 临时放弃折腾..静等更新跟进

**Comment by snow-dream** [comment]
@RikkaW 自己折腾搞定了(光速逃

**Comment by snow-dream** [comment]
@RikkaW  Can't call method "id" on unblessed reference at /usr/local/share/perl/5.20.2/Mojo/Webqq/Group.pm line 184. 发消息会报错.

**Comment by RikkaW** [comment]
@snow-dream 无法复现

**Comment by snow-dream** [comment]
@RikkaW 我中午重新搭建看看

**Comment by YHNdnzj** [comment]
@RikkaW 在哪里添加 pwd
systax error

**Comment by Lychinus** [comment]
@YHNdnzj 
 `my $client = Mojo::Webqq->new(
    log_encoding           => 'utf8',
    poll_failure_count_max => 20,
    account                => 'ffm',
    qrcode_path            => '/tmp/mojo_webqq_qrcode_ffm.png'
);`
在此处添加，记住末尾加 , 不然会报错

**Comment by YHNdnzj** [comment]
@Lychinus 我就是在这儿加的啊，systax error

**Comment by Lychinus** [comment]
@YHNdnzj 配置文件发给我看一下

**Comment by RikkaW** [comment]
@YHNdnzj 99.9% 是逗号忘了（

**Comment by YHNdnzj** [comment]
@RikkaW 还真是😂

**Comment by Lychinus** [comment]
> 还真是😂
@YHNdnzj 
(⊙﹏⊙)，我不是说过末尾加 , 不然会报错（以后多看一下报错的log，里面的提示还是很清晰的

**Comment by YHNdnzj** [comment]
@Lychinus 可是我就是加在末尾的

**Comment by Lychinus** [comment]
@YHNdnzj (⊙o⊙)？那是个英文逗号，我改一下吧

**Comment by YHNdnzj** [comment]
@Lychinus 我后来是在 qrcode_path 那一行最后补了一个逗号才成功的

**Comment by ttimasdf** [comment]
建议在配置文件中只保存密码的MD5值。毕竟传入mojo的时候也只用到了MD5，不然万一配置文件泄漏了…… 😗

**Comment by simonsmh** [comment]
@ttimasdf 8102年啦

**Comment by Mr-Bubble** [comment]
@ttimasdf 自己参考webqq的改下pl文件，然后客户端里面填入md5就可以了.  (刚更新时我就给rikka提过建议加上md5选项了,rikka说下次 ).所以就暂时自己改,等更新吧
