### ISSUE TITLE
一切就绪后，npm start报错

### ISSUE THREAD

**Issue by cuimo4183** [RikkaApps/FCM-for-Mojo#98]
你好，我的系统是Debian 7 x64 JP的VPS，上面已启动SS（冲突端口已更改），全程root用户操作。

mojoQQ（未启动，不知道怎么启动）、nodejs、git都成功安装。

最后一步npm start 报错了。。。。还望指教，谢谢

---------------------------------------------
报错信息如下：
控制台：
> ffm@0.5.3 start /FCM-for-Mojo-Server
> node node/index.js

/FCM-for-Mojo-Server/node/index.js:142
    let body;
    ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:140:18)
    at node.js:1043:3

npm ERR! Linux 3.2.0-4-amd64
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v4.8.7
npm ERR! npm  v2.15.11
npm ERR! code EXXXXXXE
npm ERR! ffm@0.5.3 start: `node node/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the ffm@0.5.3 start script 'node node/index.js'.
npm ERR! This is most likely a problem with the ffm package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node node/index.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ffm
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls ffm
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /FCM-for-Mojo-Server/npm-debug.log

npm-debug.log：
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@2.15.11
3 info using node@v4.8.7
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info prestart ffm@0.5.3
6 info start ffm@0.5.3
7 verbose unsafe-perm in lifecycle true
8 info ffm@0.5.3 Failed to exec start script
9 verbose stack Error: ffm@0.5.3 start: `node node/index.js`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:862:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:222:5)
10 verbose pkgid ffm@0.5.3
11 verbose cwd /FCM-for-Mojo-Server
12 error Linux 3.2.0-4-amd64
13 error argv "/usr/bin/node" "/usr/bin/npm" "start"
14 error node v4.8.7
15 error npm  v2.15.11
16 error code EXXXXXXE
17 error ffm@0.5.3 start: `node node/index.js`
17 error Exit status 1
18 error Failed at the ffm@0.5.3 start script 'node node/index.js'.
18 error This is most likely a problem with the ffm package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     node node/index.js
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs ffm
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls ffm
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]

**Comment by RikkaW** [comment]
@cuimo4183 更新一下 node.js 吗（

**Comment by cuimo4183** [comment]
@RikkaW 你好 node -v显示版本为v4.8.7，需要9？

**Comment by RikkaW** [comment]
@cuimo4183 不清楚.. 反正 4 太旧了..（

**Comment by cuimo4183** [comment]
@RikkaW 确实是nodejs的版本，使用n工具升级失败，最后用的nvm升级成8.9.4，成功启动。

不过现在服务器上可以看到消息了，不过手机端显示401 unauthorized，刚开始以为是basic_auth参数，之后我注释掉了basic_auth，结果还是这样，请问还有哪里有权限校验吗？

**Comment by cuimo4183** [comment]
问题关闭
auth的用户名密码是文件内容，我以为是文件名。。。谢谢了
